project:
  type: website
  output-dir: docs
  
website:
  title: "Fall 2024 Community Contributions"
  navbar:
    left:
      - href: projects.qmd
        text: Projects
    tools:
      - icon: github
        href: shttps://github.com/sec2238/CCFall2024.git
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, EDAV CC mon wed"

format:
  html:
    theme: vapor
    toc: true
    css: styles.css  # Include the custom CSS file

editor: source

